### PR TITLE
Fix issue #33

### PR DESCRIPTION
**Pull request by sebdenis**
Here is a proposal to fix the potential discontinuity of scroll_involute_axial_force. The problem was only due to a miscalculation for D1 and D2 chambers that use Nc instead of Ncmax near theta_d.

### CODE REVIEW

**Comment by ibell** [comment]
Sorry for the delay in reviewing this PR, slipped through the cracks.  Can you fix the PR so that it is just the change?  There's a lot of other changes too, some of them reverting other fixes.  You might want to start a new branch from the master.

**Comment by sebdenis** [comment]
I reversed some fixes from your last commit because changes added are about pockets C but do not fix issue #33 . My changes focus on pockets D and it works well.

**Comment by ibell** [comment]
So we really don't need the other block of code?  If so, sounds good to me and I'll merge this one.

**Comment by sebdenis** [comment]
Yes, this solution works well.

**Comment by ibell** [comment]
Hello! Where do we stand on this PR, I thought that we were waiting to revert some changes that had been made, or am I wrong?

**Comment by ibell** [comment]
Bad:
bad
Fixed:
fixed

**Comment by ibell** [comment]
Thanks, merging.

**Comment by sebdenis** [comment]
Hello! no there wasn't any changes to revert, I did it through the commit.
You can also close #33 I think.

**Comment by ibell** [comment]
Can you please close the issue?

**Pull request merged**
