### PR TITLE
Pistonexpander notebook

### PR DESCRIPTION
**Pull request by davideziviani**

### CODE REVIEW

**Comment by ibell** [comment]
Ok, you have a lot of dangling merges.  I'm not sure how to deal with that.

**Comment by davideziviani** [comment]
perhaps I could reclone the repository to fix that. I just realized in the last two merges there a number of old stuff

**Comment by ibell** [comment]
Yes, that might be best.  And then ONLY do development in branches.  No
commits to the master branch.  I think that might fix these merge issues.

**Comment by ibell** [comment]
See also
http://kernowsoul.com/blog/2012/06/20/4-ways-to-avoid-merge-commits-in-git/

**Comment by davideziviani** [comment]
I see.. I think when I commit a change to the designated branch, I should avoid to publish the changes on my master and then create a pull request for you. Rather, I simply create a pull request for you and once you merged it, I just sync your master with mine.

**Pull request merged**
